CREATE TABLE IF NOT EXISTS productos (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                codigo VARCHAR(50) NOT NULL,
                nombre VARCHAR(300) NOT NULL,
                descripcion TEXT NULL,
                stock DECIMAL(12,2) NOT NULL DEFAULT 0,
                precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
                umbral_stock DECIMAL(12,2) NOT NULL DEFAULT 2,
                unidad VARCHAR(20) NOT NULL DEFAULT 'UN',
                activo TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_productos_codigo (codigo)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_usuarios (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                nombre VARCHAR(160) NOT NULL,
                email VARCHAR(190) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                rol ENUM('admin','vendedor') NOT NULL DEFAULT 'vendedor',
                activo TINYINT(1) NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_crm_usuarios_email (email)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_empresas (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                rut VARCHAR(20) NOT NULL,
                razon_social VARCHAR(220) NOT NULL,
                nombre_fantasia VARCHAR(220) NULL,
                giro VARCHAR(220) NULL,
                industria VARCHAR(80) NULL,
                region VARCHAR(80) NULL,
                comuna VARCHAR(80) NULL,
                direccion VARCHAR(400) NULL,
                telefono VARCHAR(40) NULL,
                email VARCHAR(190) NULL,
                sitio_web VARCHAR(250) NULL,
                origen VARCHAR(40) NOT NULL DEFAULT 'web',
                ejecutivo_id INT UNSIGNED NULL,
                estado ENUM('prospecto','activa','inactiva') NOT NULL DEFAULT 'prospecto',
                notas TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_crm_empresas_rut (rut),
                KEY ix_crm_empresas_ejecutivo (ejecutivo_id),
                CONSTRAINT fk_crm_empresas_ejecutivo FOREIGN KEY (ejecutivo_id) REFERENCES crm_usuarios (id) ON DELETE SET NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_contactos (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                empresa_id INT UNSIGNED NOT NULL,
                nombre VARCHAR(120) NOT NULL,
                apellido VARCHAR(120) NULL,
                cargo VARCHAR(160) NULL,
                email VARCHAR(190) NULL,
                telefono VARCHAR(40) NULL,
                whatsapp VARCHAR(40) NULL,
                canal_preferido VARCHAR(40) NOT NULL DEFAULT 'email',
                es_principal TINYINT(1) NOT NULL DEFAULT 0,
                activo TINYINT(1) NOT NULL DEFAULT 1,
                notas TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                KEY ix_crm_contactos_empresa (empresa_id),
                CONSTRAINT fk_crm_contactos_empresa FOREIGN KEY (empresa_id) REFERENCES crm_empresas (id) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_oportunidades (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                codigo VARCHAR(32) NOT NULL,
                empresa_id INT UNSIGNED NOT NULL,
                contacto_id INT UNSIGNED NULL,
                titulo VARCHAR(220) NOT NULL,
                etapa VARCHAR(40) NOT NULL DEFAULT 'prospecto',
                valor_estimado DECIMAL(14,2) NOT NULL DEFAULT 0,
                probabilidad TINYINT UNSIGNED NOT NULL DEFAULT 10,
                fecha_cierre_esperada DATE NULL,
                ejecutivo_id INT UNSIGNED NULL,
                origen_canal VARCHAR(40) NOT NULL DEFAULT 'web',
                motivo_perdida VARCHAR(250) NULL,
                notas TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_crm_oportunidades_codigo (codigo),
                KEY ix_crm_opp_empresa (empresa_id),
                KEY ix_crm_opp_etapa (etapa),
                CONSTRAINT fk_crm_opp_empresa FOREIGN KEY (empresa_id) REFERENCES crm_empresas (id) ON DELETE CASCADE,
                CONSTRAINT fk_crm_opp_contacto FOREIGN KEY (contacto_id) REFERENCES crm_contactos (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_opp_ejecutivo FOREIGN KEY (ejecutivo_id) REFERENCES crm_usuarios (id) ON DELETE SET NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_cotizaciones (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                folio VARCHAR(32) NOT NULL,
                empresa_id INT UNSIGNED NOT NULL,
                contacto_id INT UNSIGNED NULL,
                oportunidad_id INT UNSIGNED NULL,
                ejecutivo_id INT UNSIGNED NULL,
                estado VARCHAR(40) NOT NULL DEFAULT 'borrador',
                fecha_emision DATE NOT NULL,
                fecha_validez DATE NULL,
                subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
                descuento DECIMAL(14,2) NOT NULL DEFAULT 0,
                iva DECIMAL(14,2) NOT NULL DEFAULT 0,
                total DECIMAL(14,2) NOT NULL DEFAULT 0,
                notas TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_crm_cotizaciones_folio (folio),
                KEY ix_crm_cot_empresa (empresa_id),
                CONSTRAINT fk_crm_cot_empresa FOREIGN KEY (empresa_id) REFERENCES crm_empresas (id) ON DELETE CASCADE,
                CONSTRAINT fk_crm_cot_contacto FOREIGN KEY (contacto_id) REFERENCES crm_contactos (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_cot_opp FOREIGN KEY (oportunidad_id) REFERENCES crm_oportunidades (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_cot_ejecutivo FOREIGN KEY (ejecutivo_id) REFERENCES crm_usuarios (id) ON DELETE SET NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_cotizacion_items (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                cotizacion_id INT UNSIGNED NOT NULL,
                producto_id INT UNSIGNED NULL,
                codigo VARCHAR(50) NOT NULL,
                descripcion VARCHAR(300) NOT NULL,
                cantidad DECIMAL(12,2) NOT NULL DEFAULT 1,
                precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
                descuento_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
                subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
                stock_al_cotizar DECIMAL(12,2) NULL,
                PRIMARY KEY (id),
                KEY ix_crm_cot_items_cot (cotizacion_id),
                KEY ix_crm_cot_items_prod (producto_id),
                CONSTRAINT fk_crm_cot_items_cot FOREIGN KEY (cotizacion_id) REFERENCES crm_cotizaciones (id) ON DELETE CASCADE,
                CONSTRAINT fk_crm_cot_items_producto FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE SET NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_actividades (
                id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                empresa_id INT UNSIGNED NULL,
                contacto_id INT UNSIGNED NULL,
                oportunidad_id INT UNSIGNED NULL,
                cotizacion_id INT UNSIGNED NULL,
                usuario_id INT UNSIGNED NULL,
                tipo VARCHAR(40) NOT NULL DEFAULT 'nota',
                canal VARCHAR(40) NOT NULL DEFAULT 'telefono',
                titulo VARCHAR(220) NOT NULL,
                descripcion TEXT NULL,
                fecha_programada DATETIME NULL,
                fecha_completada DATETIME NULL,
                estado VARCHAR(40) NOT NULL DEFAULT 'pendiente',
                resultado VARCHAR(250) NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                KEY ix_crm_act_empresa (empresa_id),
                KEY ix_crm_act_estado (estado, fecha_programada),
                CONSTRAINT fk_crm_act_empresa FOREIGN KEY (empresa_id) REFERENCES crm_empresas (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_act_contacto FOREIGN KEY (contacto_id) REFERENCES crm_contactos (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_act_opp FOREIGN KEY (oportunidad_id) REFERENCES crm_oportunidades (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_act_cot FOREIGN KEY (cotizacion_id) REFERENCES crm_cotizaciones (id) ON DELETE SET NULL,
                CONSTRAINT fk_crm_act_usuario FOREIGN KEY (usuario_id) REFERENCES crm_usuarios (id) ON DELETE SET NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
